version: "3.8"

services:
  ai-bot:
    container_name: ai-bot
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    ports:
      - "8003:80"
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.http.routers.ai-bot.rule=Host(`ai-bot.taglog.io`)"
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
