name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Copy Source Files to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "./"
          target: "/home/${{ secrets.VPS_USER }}/ai-bot"

      # - name: Replace .env file on VPS
      #   uses: appleboy/ssh-action@v0.1.3
      #   with:
      #     host: ${{ secrets.VPS_HOST }}
      #     username: ${{ secrets.VPS_USER }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       echo "${{ vars.ENV_VARS_ROOT }}" > /home/${{ secrets.VPS_USER }}/ai-bot/.env

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S /home/${{ secrets.VPS_USER }}/ai-bot/deploy.sh > /dev/null 2>&1 &
